[package]
name = "client"
version = "0.0.1"
edition = "2021"

[dependencies]
store = { path = "../store" }
anyhow = "1.0"
bevy = { version = "0.8", features = ["dynamic"] }
renet="0.0.9"
bevy_renet = "0.0.5"
bincode="1.3.1"
